

GET http://bundakraft-ramadhan.test/api/recipes_by_moments
content-type: application/json
Accept: application/json

{
    "moment": "home-chef-2024"
}

###

GET http://bundakraft-ramadhan.test/api/recipes_by_moments
content-type: application/json
Accept: application/json

{
    "moment": "menu-alfamart-2024"
}

###

GET http://bundakraft-ramadhan.test/api/user
content-type: application/json
Accept: application/json

###

POST http://bundakraft-ramadhan.test/api/request-download/test
content-type: application/json
Accept: application/json

{
    "firstname" : "Test",
    "lastname" : "DC3",
    "email" : "dean@designcub3.com",
    "date_of_birth" : "22/12/1995",
    "city" : "Jakarta Selatan",
    "phone" : "628121856261",
    "cid" : "GA.1.TEST",
    "type_of_signup" : "Form",
    "overall_opt_in_status" : "true",
    "tnc" : "true",
    "hutk" : "b478dcf1b67b8e2cff03d75de8c6e71e",
    "latitude" : "",
    "longitude" : "",
    "page" : "https://bundakraft-homechef.democube.id/",
    "page_url" : "Homechef",
    "additional_information": {
        //slug moment currently menu-alfamart-2024
        "moment": "menu-alfamart-2024",
        //recipe slug if, write all if the button clicked to the download
        "recipe": "*"
    }
}

