<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('description')->nullable();
            $table->json('variants')->nullable();
            $table->json('informations')->nullable();
            $table->integer('order')->default(0);
            $table->json('buy_link')->nullable();
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};

// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Cheddar 165g', 'Keju olahan siap saji dengan rasa gurih keju yang spesial dan tekstur yang lembut. Menghasilkan parutan yang lebih kering serta panggangan yang lebih keemasan.', '["Cheddar 175 g","Cheddar 75 g","Cheddar 35 g"]', '{"label":["Informasi Gizi","Per 1 Serving (20g)"],"field":[["Energi","70 kkal\\/kcal"],["Lemak","5 g"],["Lemak Jenuh","4.5 g"],["Protein","3.5 g"],["Karbo","4 g"],["Gula","0 g"],["Sodium","280 mg"]]}', 4, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Martabak 2kg', 'Keju olahan siap saji berkualitas yang memiliki tekstur lembut dan tidak mudah kering. Mudah diparut dan dipotong dengan rasa creamy lezat khas KRAFT.', '["Cheddar 2 Kg"]', '{"label":["Informasi Gizi","Per 1 Serving (20g)"],"field":[["Energi","70 kkal\\/kcal"],["Lemak","5 g"],["Lemak Jenuh","3.5 g"],["Protein","4 g"],["Karbo","2 g"],["Gula","0 g"],["Sodium","280 mg"]]}', 2, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Quick Melt 165g', 'Keju lezat yang mudah meleleh ketika dipanggang atau dimasak. Dapat disajikan langsung atau diolah terlebih dahulu.', '["Quick Melt 175g"]', '{"label":["Informasi Gizi","Per 1 Serving (30g)"],"field":[["Energi","100 kkal\\/kcal"],["Lemak","7 g"],["Lemak Jenuh","4.5 g"],["Protein","5 g"],["Karbo","4 g"],["Gula","1 g"],["Natrium","380 mg"],["Vitamin A","40%"],["Kalsium","20%"],["Yodium","8%"]]}', 3, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Singles Light', 'Keju lembaran siap saji untuk hidangan praktis dengan kelezatan spesial dan kalori yang lebih rendah. Tersedia dalam isi 10 lembar.', '["Singles 5 slices","Singles 10 Slices","Singles Low-Fat","Singles BBQ"]', '{"label":["Informasi Gizi","Per 1 Serving (17g)"],"field":[["Energi","50 kkal\\/kcal"],["Lemak","3.5 g"],["Lemak Jenuh","2.5 g"],["Protein","2 g"],["Karbo","2 g"],["Gula","0 g"],["Sodium","200 mg"]]}', 1, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Cheddar 70g', 'Keju dengan rasa gurih yang spesial berukuran pas untuk 1x sajian lezat sekeluarga.', '["Cheddar 75 g"]', '{"label":["Informasi Gizi","Per 1 Serving (20g)"],"field":[["Energi","70 kkal\\/kcal"],["Lemak","5 g"],["Lemak Jenuh","3.5 g"],["Protein","4 g"],["Karbo","2 g"],["Gula","0 g"],["Natrium","270 mg"],["Vitamin D","10%"],["Kalsium","20%"]]}', 5, '[{"logo":"https://bundakraft.com/images/olshop/clickindo.png","url":"https://www.klikindomaret.com/search/?key=keju%20kraft"},{"logo":"https://bundakraft.com/images/olshop/alfa_gift.jpg","url":"https://alfagift.id/b/kraft-11594"},{"logo":"https://bundakraft.com/images/olshop/blibli.png","url":"https://www.blibli.com/merchant/kraft-official-store/KRS-60040?promoTab=false"},{"logo":"https://bundakraft.com/images/olshop/shopee.jpg","url":"https://shopee.co.id/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https://bundakraft.com/images/olshop/tokped.jpg","url":"https://www.tokopedia.com/mondelez/etalase/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Cheddar 30g', 'Keju olahan siap saji dalam ukuran pas untuk camilan lezat kapan pun dan di mana pun', '["Cheddar 30 g"]', '{"label":["Informasi Gizi","Per 1 Serving (20g)"],"field":[["Energi","70 kkal\\/kcal"],["Lemak","5 g"],["Lemak Jenuh","3.5 g"],["Protein","4 g"],["Karbo","3 g"],["Gula","0 g"],["Natrium","270 mg"],["Vitamin D","10%"],["Kalsium","20%"]]}', 6, '[{"logo":"https://bundakraft.com/images/olshop/clickindo.png","url":"https://www.klikindomaret.com/search/?key=keju%20kraft"},{"logo":"https://bundakraft.com/images/olshop/alfa_gift.jpg","url":"https://alfagift.id/b/kraft-11594"},{"logo":"https://bundakraft.com/images/olshop/blibli.png","url":"https://www.blibli.com/merchant/kraft-official-store/KRS-60040?promoTab=false"},{"logo":"https://bundakraft.com/images/olshop/shopee.jpg","url":"https://shopee.co.id/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https://bundakraft.com/images/olshop/tokped.jpg","url":"https://www.tokopedia.com/mondelez/etalase/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Singles Regular', 'Keju lembaran siap saji untuk hidangan praktis dengan kelezatan spesial yang penuh kalsium. Tersedia dalam isi 5 dan 10 lembar.', '["Singles Regular 5s","Singles Regular 10s"]', '{"label":["Informasi Gizi","Per 1 Serving (17g)"],"field":[["Energi","50 kkal\\/kcal"],["Lemak","3.5 g"],["Lemak Jenuh","2.5 g"],["Protein","3 g"],["Karbo","2 g"],["Gula","0 g"],["Natrium","230 mg"],["Vitamin D","6%"],["Kalsium","20%"],["Yodium","8%"]]}', 7, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Singles BBQ', 'Keju lembaran siap saji untuk hidangan praktis dengan kelezatan rasa Barbeque yang spesial. Tersedia dalam isi 5 dan 10 lembar', '["Singles BBQ 5s","Singles BBQ 10s"]', '{"label":["Informasi Gizi","Per 1 Serving (17g)"],"field":[["Energi","60 kkal\\/kcal"],["Lemak","4 g"],["Lemak Jenuh","3.5 g"],["Protein","2 g"],["Karbo","3 g"],["Gula","0 g"],["Natrium","220 mg"],["Vitamin D","8%"],["Kalsium","20%"]]}', 8, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 0);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT Cheddar Cheese 2kg', 'Keju olahan siap saji berkualitas yang memiliki tekstur dan hasil parutan yang baik. Memberikan warna kuning keemasan ketika dipanggang dan rasa gurih lezat khas KRAFT yang kuat.', '["Cheddar Cheese 2kg"]', '{"label":["Informasi Gizi","Per 1 Serving (30g)"],"field":[["Energi","100 kkal\\/kcal"],["Lemak","7 g"],["Lemak Jenuh","6 g"],["Protein","12 g"],["Karbo","3 g"],["Gula","0 g"],["Natrium","340 mg"],["Kalsium","25%"]]}', 8, '[{"logo":"https://bundakraft.com/images/olshop/clickindo.png","url":"https://www.klikindomaret.com/search/?key=keju%20kraft"},{"logo":"https://bundakraft.com/images/olshop/alfa_gift.jpg","url":"https://alfagift.id/b/kraft-11594"},{"logo":"https://bundakraft.com/images/olshop/blibli.png","url":"https://www.blibli.com/merchant/kraft-official-store/KRS-60040?promoTab=false"},{"logo":"https://bundakraft.com/images/olshop/shopee.jpg","url":"https://shopee.co.id/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https://bundakraft.com/images/olshop/tokped.jpg","url":"https://www.tokopedia.com/mondelez/etalase/kraft"}]', 1);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT  Milky Soft', 'Keju lezat yang creamy dan lembut, cocok diolah untuk berbagai hidangan lauk pauk atau dinikmati secara langsung.', '["Milky Soft 165g"]', '{"label":["Informasi Gizi","Per 1 Serving (30g)"],"field":[["Energi","90 kkal\\/kcal"],["Lemak","7 g"],["Lemak Jenuh","4 g"],["Kolesterol","4 mg"],["Protein","3 g"],["Karbo","4 g"],["Gula","1 g"],["Natrium","240 mg"],["Kalsium","10%"]]}', 0, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 0);
// INSERT INTO `products` (`name`, `description`, `variants`, `informations`, `order`, `buy_link`, `is_active`) VALUES ('KRAFT All in One 165g', 'Keju olahan siap saji dengan rasa keju yang lezat, dapat digunakan untuk semua aplikasi dan memberikan solusi hemat dengan kualitas KRAFT', '["KRAFT All In One 165g"]', '{"label":["Informasi Gizi","Per 1 Serving (30g)"],"field":[["Energi ","50 kkal\\/kcal"],["Lemak","4 g"],["Lemak Jenuh","1.5 g"],["Protein ","2 g"],["Karbo ","3 g"],["Gula ","0 g"],["Natrium ","310 mg"]]}', 9, '[{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/clickindo.png","url":"https:\\/\\/www.klikindomaret.com\\/search\\/?key=keju%20kraft"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/alfa_gift.jpg","url":"https:\\/\\/alfagift.id\\/b\\/kraft-11594"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/blibli.png","url":"https:\\/\\/www.blibli.com\\/merchant\\/kraft-official-store\\/KRS-60040?promoTab=false"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/shopee.jpg","url":"https:\\/\\/shopee.co.id\\/mondelezofficial?shopCollection=5703493#product_list"},{"logo":"https:\\/\\/bundakraft.com\\/images\\/olshop\\/tokped.jpg","url":"https:\\/\\/www.tokopedia.com\\/mondelez\\/etalase\\/kraft"}]', 1);

